### ISSUE TITLE
Error on Ruby v 1.9.3 from DateTime::new!

### ISSUE THREAD

**Issue by ghost** [datamapper/dm-core#144]
``` ruby
require 'rubygems'
require 'dm-migrations'
require 'dm-timestamps'

class Foo
  include DataMapper::Resource
  property :id,         Serial 
  property :name,       String
  timestamps :at
end

DataMapper.setup(:default, 'sqlite3::memory:')
DataMapper.auto_migrate! if defined?(DataMapper)

#=> Foo.create(:name => 'foo')
#=> Foo.first
```

```NoMethodError: undefined method`new!' for DateTime:Class
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-do-adapter-1.2.0.rc2/lib/dm-do-adapter/adapter.rb:153:in `next!'
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-do-adapter-1.2.0.rc2/lib/dm-do-adapter/adapter.rb:153:in`block in read'
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-do-adapter-1.2.0.rc2/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-do-adapter-1.2.0.rc2/lib/dm-do-adapter/adapter.rb:141:in`read'
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-core-1.2.0.rc2/lib/dm-core/repository.rb:162:in `read'
from $HOME/.rvm/gems/ruby-1.9.3-preview1/gems/dm-core-1.2.0.rc2/lib/dm-core/model.rb:377:in`first'
from $HOME/.rvm/rubies/ruby-1.9.3-preview1/bin/irb:16:in `<main>'

```

Same thing on 1.9.3-rc1
```

**Comment by heaven** [comment]
Still having this:
```
data_mapper (1.2.0)
dm-aggregates (1.2.0)
dm-constraints (1.2.0)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
dm-timestamps (1.2.0)
dm-transactions (1.2.0)
dm-types (1.2.2)
dm-validations (1.2.0)
```

Ruby: `1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]`
