### ISSUE TITLE
DataMapper::Repository#read with an invalid query returns an ambiguous result

### ISSUE THREAD

**Issue by halorgium** [datamapper/dm-core#16]
If you ask a Repository to read the records for a valid query which returns an empty set, you get an empty set. 
If you ask a Repository to read the records for an invalid query, you get an empty set. 

It is impossible to determine the difference between these results. 

Can we change the behaviour for an invalid query to raise an error?

https://github.com/datamapper/dm-core/blob/master/lib/dm-core/repository.rb#L160-163

**Comment by tpitale** [comment]
@mbj Any interest in tackling this still?

**Comment by tpitale** [comment]
I haven't made a PR yet, but this is where I was headed: https://github.com/tpitale/dm-core/commit/83f432c74252b1757b710d1bc3e3f76ba45ec089

**Comment by tpitale** [comment]
Oh wait, I did add a PR … #295.

**Comment by mbj** [comment]
> @mbj Any interest in tackling this still?

No, sorry.
