### ISSUE TITLE
Postgresql Schemas

### ISSUE THREAD

**Issue by st1gma** [datamapper/dm-core#265]
Does DataMapper have support for PostgreSQL schemas? If so, how would I go about passing the schema name into setup?

**Comment by wkretzsch** [comment]
+1 for using custom schema names

**Comment by st1gma** [comment]
I totally forgot about this. You can just execute a query directly on the DB "set search_path 'yourschema'" then go about your business with dm as you normally would. As luissalazar said you could monkey patch but this should definitely be part of the library otherwise it is not fully compliant with PG.

**Comment by nbluis** [comment]
:+1: 

And thanks to @st1gma to provide a "workaround" to solve it. :smile:

**Comment by tpitale** [comment]
You can also add to the `DataMapper.setup` call the option for `search_path`:

```ruby
# Get all the options that came from config e.g., database.yml with dm-rails
options = DataMapper.repository(:default).adapter.options

# Set up again, with different search_path
DataMapper.setup(:default, options.merge(search_path: "custom_schema, public"))
```

Obviously, you'd have to adjust this a little for your case.
