### ISSUE TITLE
DataMapper adds `DEFAULT NULL` to a required field if no other default is specified

### ISSUE THREAD

**Issue by brandondrew** [datamapper/dm-core#275]
I'm getting an error when I use DataMapper's `auto_upgrade!` method to add fields in an SQLite3 db based on the properties defined in my code:

> DataObjects::SyntaxError at /history  
> Cannot add a NOT NULL column with default value NULL  

An example of an offending line would be:

    property :fieldname, Text,  required: true

The error goes away if I (a) remove the line, (b) remove `required: true`, (c) change `true` to `false`, or (d) add a default value.

SQLite *does **not*** require a default value to be specified for every field, so this problem is definitely with DataMapper, not SQLite.  

I'd like the required field to be enforced at the database level,  but DataMapper is preventing that by adding a NULL default when I don't specify any other default.  (Having *any* default is just as bad as having a NULL value.  I need to have *real* data entered into this field.)

Slightly more info at:  http://stackoverflow.com/q/26832257/241142

**Comment by tpitale** [comment]
This is likely something for dm-migrations project. I'll move it there.
