### ISSUE TITLE
register_hooks and ruby 2

### ISSUE THREAD

**Issue by tpitale** [datamapper/dm-core#277]
Theres a usage of register_hook (https://github.com/datamapper/dm-core/blob/master/lib/dm-core/support/hook.rb#L171) in dm-is-list (using `inherited`) that breaks in later version of ruby (maybe 2.1+, I'm still going backwards).

I think this can be fixed by setting `true` as the second arg to `respond_to?` on the above line.

I'm testing locally and will report back.

**Comment by tpitale** [comment]
Guessing based on this article :-) http://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html

**Comment by tpitale** [comment]
Yes, that fixes it. Not sure what else it might break, though.

Relates to https://github.com/datamapper/dm-is-list/issues/6

**Comment by tillsc** [comment]
I do not think that it would be a good Idea to be able to hook upon private / protected methods. In my Ruby 1.9.3 setup the datamapper model's `inherited` methods are public. DM seems to change this somewhere since it is private by Ruby default (I've tested it with 1.8, 1.9 and 2.0).

Maybe we should try to find out why `inherited` is public under 1.9 and something else under 2.x

**Comment by tpitale** [comment]
I don't disagree that hooking those is weird.

I'm curious why `inherited` is the thing we want to hook, either … seems iffy.

According to http://ruby-doc.org/core-1.9.3/Class.html#method-i-inherited `inherited` is private. This is true in 2.0.0, 2.1.0, 2.2.0.

So I'm not sure this is working in any case.

**Comment by tillsc** [comment]
Here is a minimal test case illustrating this in Ruby 1.9.3: https://gist.github.com/tillsc/2960e3257461531b9e6b

**Comment by tpitale** [comment]
Sooooo, DM changes the visibility of that method … maybe that isn't working any longer in new ruby versions? I'll experiment more when I get home from work. Thanks!

**Comment by tpitale** [comment]
I just tried your gist on ruby 2.2.0p0. With the datamapper resource class, `inherited` is a public method.

So confusing. I'm wondering now if this is a load order issue with dm-is-list trying to register hooks for inherited before resource makes it public?

Maybe @dkubb or @solnic know what's up with the visibility change?

**Comment by tpitale** [comment]
Oh wait, I did that test on released gems 1.2.0 of DM. Let me try with masters.

**Comment by tpitale** [comment]
Aha! On master of dm-core (and the rest of dm-*) your example gist is different. Here's what I get: https://gist.github.com/tpitale/42e5ebaf04f18edf85ba Still don't know what changed in DM. But it's definitely not a change in ruby (or at least not just in ruby).

**Comment by tillsc** [comment]
I could not reproduce the issue with Ruby 2.1.5, 2.2.0 nor 2.2.1. Did you require more than 'dm-core'?

**Comment by tpitale** [comment]
You're right, I was running with rails and all the dm-* gems I use. So I made this test: https://gist.github.com/tpitale/b67e1f86763ba6ea0b75

It looks like, at least in this case, that dm-validations made inherited switch back from public to private.

**Comment by tpitale** [comment]
If I remove dm-validations from the list … nothing else changes it back from public to private.

**Comment by tpitale** [comment]
Should I close this and move over to dm-validations?

**Comment by tpitale** [comment]
Hrmmm: https://github.com/datamapper/dm-validations/blob/master/lib/data_mapper/validation.rb#L96

**Comment by tpitale** [comment]
Hrm: https://github.com/datamapper/dm-validations/commit/afd1e353#diff-05f5267ccc55bd15fa767fade72cf669L184

The api is private, but it does not appear that the method is private. I will change locally and see if that fixes, then send a PR to dm-validations.

**Comment by tpitale** [comment]
And boom: https://github.com/datamapper/dm-validations/commit/145100db6dc6e9f6baab9cb63ba5bedd31e27ea1#diff-3fa714c2908862ba7f6e400ced298674

**Comment by tillsc** [comment]
Good finding! :) We should propose to roll that one back

**Comment by tpitale** [comment]
I'll send a PR now.

**Comment by tpitale** [comment]
PR sent: https://github.com/datamapper/dm-validations/pull/73
