### ISSUE TITLE
Bug on create unique index with scopes

### ISSUE THREAD

**Issue by J-F-Liu** [datamapper/dm-core#281]
For the following code:
`property :modelnumber, String, :unique => [:brand, :name], :required => true`

The generated SQL statement is:
~~~~~~~
CREATE UNIQUE INDEX "unique_products_brand" ON "products" ("modelnumber");
CREATE UNIQUE INDEX "unique_products_name" ON "products" ("modelnumber");
~~~~~~~
The correct SQL statement should be:
`CREATE UNIQUE INDEX "unique_products_modelnumber" ON "products" ("modelnumber", "brand", "name")`

**Comment by tillsc** [comment]
Belongs to datamapper/dm-validations#43

**Comment by J-F-Liu** [comment]
The validation works if I first create the table then add the unique argument.
I created a fix on property_set.rb and passed test on table creation, will send PR later.

**Comment by tpitale** [comment]
@J-F-Liu is the rest of your model like this?

```ruby
property :name, String
property :brand, String
```

If so, I think the syntax for a unique index for these fields would be to use a symbol, like this:

```ruby
property :modelnumber String, unique: :model_brand_name
property :brand String, unique: :model_brand_name
property :name String, unique: :model_brand_name
```

That is the intended use.
