### ISSUE TITLE
Low performance on RPI2

### ISSUE THREAD

**Issue by brbrr** [datamapper/dm-core#293]
DataMapper using sqlite/pg adapter shows very slow performance on getting records from table. 
I trying to get all my records, and it took ~10sec to return 5000 records.

My model:

```
class Report
  include DataMapper::Resource
  property :id, Serial
  property :humidity, Float, required: true
  property :temperature, Float, required: true
  property :preasure, Float, required: true
  property :created_at, DateTime
end
```

whole app code could be found [`here`](https://github.com/brbrr/weather-api)
I've installed ActiveRecord to compare, and wow it give me 1-2sec.
Also I notice that DM is using only 1 cpu, while activerecord - up to 4 cpu's

Same code on Heroku is running quite fast(using free account), so I suppose that performance issues is related to configs.

**Comment by tpitale** [comment]
If you're starting a new project I would not advise using DM. It is not being actively maintained. I would just checking out Sequel.
