### ISSUE TITLE
trying to trigger an additional save (without validations / callbacks) inside an after :save callback

### ISSUE THREAD

**Issue by solnic** [datamapper/dm-core#78]
This is admittedly a strange situation, but I was under the impression that this should work: 

http://gist.github.com/255202

At the very least, the save! / update! operation shouldn't return true here.

---

Created by **Nick Plante** - 2009-12-13 01:48:43 UTC

Original Lighthouse ticket: [http://datamapper.lighthouseapp.com/projects/20609/tickets/1152](http://datamapper.lighthouseapp.com/projects/20609/tickets/1152)

**Comment by wkretzsch** [comment]
I am still encountering this issue with datamapper v1.2.0 (see my [SO post](https://stackoverflow.com/questions/32425263/why-cant-i-call-self-save-inside-of-a-ruby-datamapper-after-create-callback) ).  Is this supposed to have been fixed?
